export const previewDishes = [
  {
    id: 'preview-cantonese-fish',
    stallId: 'n-protein',
    name: '清鲜蒸鱼套餐',
    price: 18,
    taste: '清鲜',
    cuisine: '粤菜',
    ingredients: ['龙利鱼', '玉米', '西兰花', '米饭'],
    tags: ['粤味清鲜', '低脂', '今日推荐'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 468, protein: 36, fat: 10, carbs: 56 },
    rating: 4.9,
    reviewCount: 238,
    sales: 1120,
    image: '🐟',
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',
    description: '鱼肉鲜嫩，搭配时蔬和米饭，适合想吃得清爽又有饱腹感的一餐。'
  },
  {
    id: 'preview-southwest-chicken',
    stallId: 's-local',
    name: '湘味小炒鸡饭',
    price: 16,
    taste: '香辣',
    cuisine: '湘菜',
    ingredients: ['鸡腿肉', '青椒', '小米椒', '米饭'],
    tags: ['西南湘辣', '下饭', '大份量'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 658, protein: 34, fat: 20, carbs: 82 },
    rating: 4.8,
    reviewCount: 196,
    sales: 980,
    image: '🌶️',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80',
    description: '鲜辣入味，鸡肉和米饭搭配得刚刚好，适合想吃一顿热乎重口的午餐。'
  },
  {
    id: 'preview-northwest-noodle',
    stallId: 'n-halal',
    name: '西北牛肉宽面',
    price: 15,
    taste: '咸鲜',
    cuisine: '西北',
    ingredients: ['牛肉', '宽面', '萝卜', '香菜'],
    tags: ['西北面食', '热汤', '清真'],
    halal: true,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 612, protein: 31, fat: 17, carbs: 84 },
    rating: 4.8,
    reviewCount: 174,
    sales: 890,
    image: '🍜',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80',
    description: '汤底热乎，宽面筋道，适合需要一份扎实能量的课后时段。'
  },
  {
    id: 'preview-eastasian-roll',
    stallId: 'c-fast',
    name: '日式照烧饭团',
    price: 12,
    taste: '咸鲜',
    cuisine: '日式',
    ingredients: ['米饭', '鸡肉', '海苔', '玉米'],
    tags: ['日韩风味', '便携', '低价'],
    halal: false,
    mealTypes: ['breakfast', 'lunch'],
    nutrition: { calories: 382, protein: 18, fat: 9, carbs: 58 },
    rating: 4.6,
    reviewCount: 126,
    sales: 760,
    image: '🍙',
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=80',
    description: '方便携带的日式饭团，适合课间快速补充能量。'
  },
  {
    id: 'preview-light-salad',
    stallId: 'c-light',
    name: '牛油果虾仁能量碗',
    price: 22,
    taste: '清爽',
    cuisine: '轻食',
    ingredients: ['虾仁', '牛油果', '生菜', '玉米'],
    tags: ['轻食早餐', '高蛋白', '低负担'],
    halal: false,
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    nutrition: { calories: 498, protein: 33, fat: 18, carbs: 45 },
    rating: 4.7,
    reviewCount: 104,
    sales: 680,
    image: '🥗',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
    description: '虾仁、牛油果和蔬菜组合，适合学习日或运动后的轻盈一餐。'
  },
  {
    id: 'preview-campus-beef-rice',
    stallId: 'e-fast',
    name: '黑椒牛肉双拼饭',
    price: 14,
    taste: '黑椒',
    cuisine: '快餐',
    ingredients: ['牛肉', '豆腐', '米饭', '西兰花'],
    tags: ['校园快餐', '双拼', '高性价比'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 628, protein: 32, fat: 18, carbs: 80 },
    rating: 4.5,
    reviewCount: 92,
    sales: 620,
    image: '🍱',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80',
    description: '牛肉和豆腐双拼，出餐快、价格稳，适合赶课时快速解决一餐。'
  }
];
