export const canteens = [
  {
    id: 'campus-main',
    name: '中央餐饮区',
    location: '校园中心区',
    hours: '06:00 - 22:00',
    crowdLevel: 55,
    tags: ['中央校区', '综合服务'],
    description: '中央餐饮区，下设学苑餐厅和中央风味食堂。',
    parentId: null,
    canteenType: 'primary',
    image: '🏫',
    imageUrl: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'north-zone', name: '北苑餐饮区', location: '北区生活广场', hours: '06:00 - 21:30', crowdLevel: 68,
    tags: ['北区', '近宿舍'], description: '服务北区宿舍群，下设综合食堂与社区食堂。', parentId: null, canteenType: 'primary', image: '🏢',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'south-zone', name: '南湖餐饮区', location: '南区体育中心', hours: '06:30 - 23:00', crowdLevel: 46,
    tags: ['南区', '夜宵'], description: '服务体育馆与南区宿舍，下设南湖食堂和运动主题食堂。', parentId: null, canteenType: 'primary', image: '🏠',
    imageUrl: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'east-zone', name: '东苑餐饮区', location: '东区图书馆旁', hours: '07:00 - 21:30', crowdLevel: 39,
    tags: ['东区', '安静就餐'], description: '服务图书馆与实验楼，下设东苑餐厅和科创食堂。', parentId: null, canteenType: 'primary', image: '🏛️',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'north',
    name: '北苑食堂',
    location: '北区生活广场一层',
    hours: '06:30 - 20:30',
    crowdLevel: 72,
    tags: ['早餐丰富', '高性价比', '近宿舍'],
    description: '北区学生最常去的综合食堂，早餐、盖饭、粉面和清真档口集中。',
    parentId: 'north-zone',
    canteenType: 'sub',
    image: '🏢',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'central',
    name: '学苑餐厅',
    location: '教学楼群西侧',
    hours: '10:30 - 21:00',
    crowdLevel: 58,
    tags: ['午餐热门', '快餐', '低脂选择'],
    description: '靠近教学区，适合课间快速就餐，也提供轻食和低脂套餐。',
    parentId: 'campus-main',
    canteenType: 'sub',
    image: '🏛️',
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=82'
  },
  {
    id: 'south',
    name: '南湖食堂',
    location: '南区体育馆旁',
    hours: '07:00 - 22:00',
    crowdLevel: 43,
    tags: ['夜宵', '地方风味', '大份量'],
    description: '晚餐和夜宵选择多，适合运动后补充能量。',
    parentId: 'south-zone',
    canteenType: 'sub',
    image: '🏠',
    imageUrl: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?auto=format&fit=crop&w=1200&q=82'
  },
  { id: 'north-community', name: '北苑社区食堂', location: '北区宿舍 8 号楼旁', hours: '06:30 - 21:00', crowdLevel: 51, tags: ['社区食堂', '早餐'], description: '面向北区宿舍的便捷社区食堂。', parentId: 'north-zone', canteenType: 'sub', image: '🍲', imageUrl: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1200&q=82' },
  { id: 'central-flavor', name: '中央风味食堂', location: '大学生活动中心东侧', hours: '10:00 - 21:30', crowdLevel: 63, tags: ['地方风味', '聚餐'], description: '汇集不同地域口味和特色套餐。', parentId: 'campus-main', canteenType: 'sub', image: '🍽️', imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=82' },
  { id: 'south-sports', name: '南区运动食堂', location: '体育馆东门', hours: '07:00 - 22:30', crowdLevel: 36, tags: ['运动营养', '夜宵'], description: '面向运动人群的高蛋白和能量补给食堂。', parentId: 'south-zone', canteenType: 'sub', image: '💪', imageUrl: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?auto=format&fit=crop&w=1200&q=82' },
  { id: 'east-library', name: '东苑餐厅', location: '图书馆一层东侧', hours: '07:00 - 20:30', crowdLevel: 34, tags: ['轻食', '安静'], description: '适合学习间隙快速就餐。', parentId: 'east-zone', canteenType: 'sub', image: '📚', imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=82' },
  { id: 'east-innovation', name: '科创食堂', location: '实验楼群南侧', hours: '10:30 - 21:30', crowdLevel: 44, tags: ['快餐', '夜间供餐'], description: '为实验楼和创新中心提供快速套餐。', parentId: 'east-zone', canteenType: 'sub', image: '🔬', imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=82' },
];

export const stalls = [
  { id: 'n-protein', canteenId: 'north', floor: '1F', name: '元气蛋白餐', category: '健康轻食', rating: 4.8, avgPrice: 16, open: true, description: '鸡胸肉、鱼肉、豆制品和杂粮饭为主。' },
  { id: 'n-halal', canteenId: 'north', floor: '1F', name: '西北清真面馆', category: '清真面食', rating: 4.7, avgPrice: 15, open: true, description: '牛肉面、拌面、羊肉汤饭，全部清真。' },
  { id: 'c-fast', canteenId: 'central', floor: '2F', name: '课间快餐', category: '盖饭套餐', rating: 4.4, avgPrice: 13, open: true, description: '出餐快，适合午休时间紧张的学生。' },
  { id: 'c-light', canteenId: 'central', floor: '1F', name: '绿野轻食', category: '低脂沙拉', rating: 4.6, avgPrice: 18, open: true, description: '蔬菜、优质蛋白和低脂酱汁搭配。' },
  { id: 's-local', canteenId: 'south', floor: '1F', name: '湖畔小炒', category: '地方小炒', rating: 4.5, avgPrice: 17, open: true, description: '现炒热菜，口味选择丰富。' },
  { id: 's-energy', canteenId: 'south', floor: '2F', name: '运动补给站', category: '高能套餐', rating: 4.7, avgPrice: 20, open: true, description: '高蛋白、高碳水，适合训练后恢复。' },
  { id: 'n-cold', canteenId: 'north', floor: '1F', name: '清凉小食坊', category: '冷食小吃', rating: 4.5, avgPrice: 12, open: true, description: '凉皮、凉面、冷饮和消暑小吃。' },
  { id: 'n-breakfast', canteenId: 'north-community', floor: '1F', name: '晨光早餐铺', category: '早餐粥点', rating: 4.4, avgPrice: 8, open: true, description: '粥、包点、鸡蛋和豆浆。' },
  { id: 'c-flavor', canteenId: 'central-flavor', floor: '1F', name: '八方风味档', category: '地方风味', rating: 4.6, avgPrice: 16, open: true, description: '每日轮换地方特色套餐。' },
  { id: 's-sports', canteenId: 'south-sports', floor: '1F', name: '训练后厨房', category: '运动营养', rating: 4.7, avgPrice: 19, open: true, description: '高蛋白套餐与运动饮品。' },
  { id: 'e-light', canteenId: 'east-library', floor: '1F', name: '书香轻食', category: '轻食简餐', rating: 4.5, avgPrice: 15, open: true, description: '低负担沙拉、三明治和咖啡。' },
  { id: 'e-fast', canteenId: 'east-innovation', floor: '1F', name: '科创快餐', category: '快捷套餐', rating: 4.3, avgPrice: 13, open: true, description: '实验间隙也能快速取餐。' },
];

export const dishes = [
  {
    id: 'd-chicken-bowl',
    stallId: 'n-protein',
    name: '香煎鸡胸杂粮饭',
    price: 16,
    taste: '黑椒',
    cuisine: '轻食',
    ingredients: ['鸡胸肉', '糙米', '西兰花', '玉米'],
    tags: ['高蛋白', '低脂', '减脂推荐'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 486, protein: 38, fat: 11, carbs: 58 },
    expandedNutrition: { fiber: 4.2, sodium: 520, sugar: 3, calcium: 45, iron: 2.8 },
    rating: 4.8,
    reviewCount: 126,
    sales: 530,
    image: '🍱',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',
    description: '主食、蛋白和蔬菜比例均衡，适合减脂和维持体重。'
  },
  {
    id: 'd-fish-set',
    stallId: 'n-protein',
    name: '番茄龙利鱼套餐',
    price: 18,
    taste: '酸甜',
    cuisine: '轻食',
    ingredients: ['龙利鱼', '番茄', '米饭', '生菜'],
    tags: ['高蛋白', '低热量', '清爽'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 438, protein: 34, fat: 8, carbs: 54 },
    expandedNutrition: { fiber: 2.8, sodium: 480, sugar: 6, calcium: 55, iron: 1.9 },
    rating: 4.7,
    reviewCount: 88,
    sales: 390,
    image: '🐟',
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',
    description: '鱼肉蛋白优质，脂肪低，口味清爽。'
  },
  {
    id: 'd-beef-noodle',
    stallId: 'n-halal',
    name: '清真牛肉拉面',
    price: 15,
    taste: '咸鲜',
    cuisine: '西北',
    ingredients: ['牛肉', '拉面', '萝卜', '香菜'],
    tags: ['清真', '热汤', '高碳水'],
    halal: true,
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    nutrition: { calories: 620, protein: 29, fat: 18, carbs: 86 },
    expandedNutrition: { fiber: 2.1, sodium: 890, sugar: 4, calcium: 38, iron: 3.5 },
    rating: 4.7,
    reviewCount: 153,
    sales: 720,
    image: '🍜',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80',
    description: '热汤面食，饱腹感强，适合常规午晚餐。'
  },
  {
    id: 'd-egg-tomato',
    stallId: 'c-fast',
    name: '番茄鸡蛋盖饭',
    price: 11,
    taste: '酸甜',
    cuisine: '家常',
    ingredients: ['鸡蛋', '番茄', '米饭'],
    tags: ['高性价比', '家常', '快餐'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 560, protein: 20, fat: 17, carbs: 80 },
    expandedNutrition: { fiber: 1.8, sodium: 620, sugar: 8, calcium: 62, iron: 2.2 },
    rating: 4.3,
    reviewCount: 210,
    sales: 980,
    image: '🍛',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80',
    description: '价格低、出餐快，是高频基础餐。'
  },
  {
    id: 'd-salad',
    stallId: 'c-light',
    name: '牛油果虾仁能量碗',
    price: 22,
    taste: '清爽',
    cuisine: '轻食',
    ingredients: ['虾仁', '牛油果', '生菜', '藜麦'],
    tags: ['高蛋白', '健康脂肪', '维持推荐'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 512, protein: 32, fat: 21, carbs: 48 },
    expandedNutrition: { fiber: 6.5, sodium: 380, sugar: 4, calcium: 78, iron: 3.2 },
    rating: 4.6,
    reviewCount: 64,
    sales: 210,
    image: '🥗',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
    description: '蛋白和健康脂肪充足，预算较高时适合维持体重。'
  },
  {
    id: 'd-tofu',
    stallId: 's-local',
    name: '麻婆豆腐双拼饭',
    price: 13,
    taste: '麻辣',
    cuisine: '川湘',
    ingredients: ['豆腐', '牛肉末', '米饭', '青菜'],
    tags: ['下饭', '微辣', '高性价比'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 690, protein: 25, fat: 26, carbs: 88 },
    expandedNutrition: { fiber: 3.1, sodium: 780, sugar: 5, calcium: 120, iron: 4.1 },
    rating: 4.5,
    reviewCount: 132,
    sales: 610,
    image: '🌶️',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80',
    description: '口味重、饱腹感强，适合预算有限且能吃辣的学生。'
  },
  {
    id: 'd-bulk',
    stallId: 's-energy',
    name: '牛肉鸡蛋增肌饭',
    price: 21,
    taste: '黑椒',
    cuisine: '运动餐',
    ingredients: ['牛肉', '鸡蛋', '米饭', '土豆'],
    tags: ['增肌推荐', '高蛋白', '高碳水'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 760, protein: 46, fat: 24, carbs: 92 },
    expandedNutrition: { fiber: 3.5, sodium: 720, sugar: 6, calcium: 58, iron: 4.8 },
    rating: 4.8,
    reviewCount: 77,
    sales: 280,
    image: '🥩',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
    description: '蛋白和碳水都高，适合力量训练日。'
  },
  {
    id: 'd-oat',
    stallId: 'c-light',
    name: '燕麦酸奶早餐杯',
    price: 9,
    taste: '酸甜',
    cuisine: '早餐',
    ingredients: ['燕麦', '酸奶', '香蕉', '坚果'],
    tags: ['早餐', '低价', '高纤维'],
    halal: false,
    mealTypes: ['breakfast'],
    nutrition: { calories: 330, protein: 14, fat: 9, carbs: 52 },
    expandedNutrition: { fiber: 5.8, sodium: 120, sugar: 16, calcium: 180, iron: 2.4 },
    rating: 4.4,
    reviewCount: 45,
    sales: 190,
    image: '🥣',
    imageUrl: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&w=900&q=80',
    description: '轻负担早餐，适合赶早课。'
  },
  {
    id: 'd-liangpi',
    stallId: 'n-cold',
    name: '陕西凉皮',
    price: 12,
    taste: '酸辣',
    cuisine: '西北',
    ingredients: ['凉皮', '黄瓜', '面筋', '醋', '辣椒油', '蒜'],
    tags: ['消暑', '清爽', '酸辣', '冷食'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 380, protein: 20, fat: 9, carbs: 52 },
    expandedNutrition: { fiber: 2.5, sodium: 680, sugar: 8, calcium: 35, iron: 2.1 },
    rating: 4.6,
    reviewCount: 98,
    sales: 420,
    image: '🥢',
    imageUrl: 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=900&q=80',
    description: '经典消暑小吃，酸辣开胃，天热时首选。'
  },
  {
    id: 'd-cold-noodle',
    stallId: 'n-cold',
    name: '韩式冷面',
    price: 14,
    taste: '酸甜',
    cuisine: '韩式',
    ingredients: ['荞麦面', '鸡蛋', '黄瓜', '泡菜', '牛肉汤'],
    tags: ['消暑', '冷食', '清爽'],
    halal: false,
    mealTypes: ['lunch', 'dinner'],
    nutrition: { calories: 420, protein: 18, fat: 10, carbs: 68 },
    expandedNutrition: { fiber: 2.0, sodium: 590, sugar: 10, calcium: 42, iron: 2.6 },
    rating: 4.5,
    reviewCount: 67,
    sales: 310,
    image: '🍜',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80',
    description: '冰爽酸甜，夏天解暑利器。'
  },
  {
    id: 'd-musubi',
    stallId: 'c-fast',
    name: '日式饭团套餐',
    price: 10,
    taste: '咸鲜',
    cuisine: '日式',
    ingredients: ['米饭', '海苔', '金枪鱼', '黄瓜'],
    tags: ['快餐', '低价', '便携'],
    halal: false,
    mealTypes: ['breakfast', 'lunch'],
    nutrition: { calories: 340, protein: 15, fat: 6, carbs: 58 },
    expandedNutrition: { fiber: 1.5, sodium: 450, sugar: 3, calcium: 28, iron: 1.6 },
    rating: 4.2,
    reviewCount: 56,
    sales: 380,
    image: '🍙',
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=80',
    description: '方便快捷，适合课间赶时间。'
  },
  { id: 'd-breakfast-set', stallId: 'n-breakfast', name: '晨光粥点套餐', price: 8, taste: '清淡', cuisine: '早餐', ingredients: ['小米粥', '鸡蛋', '包子'], tags: ['早餐', '低价', '暖胃'], halal: false, mealTypes: ['breakfast'], nutrition: { calories: 360, protein: 16, fat: 9, carbs: 52 }, expandedNutrition: { fiber: 3, sodium: 380, sugar: 4, calcium: 70, iron: 2.1 }, rating: 4.4, reviewCount: 38, sales: 260, image: '🥣', imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=900&q=80', description: '适合早课前的暖胃组合。' },
  { id: 'd-flavor-chicken', stallId: 'c-flavor', name: '风味烤鸡饭', price: 16, taste: '香辣', cuisine: '地方风味', ingredients: ['鸡腿', '米饭', '时蔬'], tags: ['招牌', '高蛋白'], halal: false, mealTypes: ['lunch', 'dinner'], nutrition: { calories: 640, protein: 35, fat: 19, carbs: 78 }, expandedNutrition: { fiber: 3.2, sodium: 690, sugar: 5, calcium: 48, iron: 3.1 }, rating: 4.6, reviewCount: 52, sales: 300, image: '🍗', imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80', description: '中央风味食堂的轮换招牌套餐。' },
  { id: 'd-sports-pasta', stallId: 's-sports', name: '鸡肉能量意面', price: 19, taste: '黑椒', cuisine: '运动餐', ingredients: ['鸡胸肉', '意面', '西兰花'], tags: ['高蛋白', '训练后'], halal: false, mealTypes: ['lunch', 'dinner'], nutrition: { calories: 710, protein: 44, fat: 17, carbs: 91 }, expandedNutrition: { fiber: 5, sodium: 610, sugar: 6, calcium: 62, iron: 3.6 }, rating: 4.7, reviewCount: 41, sales: 220, image: '🍝', imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80', description: '训练后补充蛋白和碳水。' },
  { id: 'd-library-sandwich', stallId: 'e-light', name: '全麦鸡蛋三明治', price: 13, taste: '咸鲜', cuisine: '轻食', ingredients: ['全麦面包', '鸡蛋', '生菜'], tags: ['便携', '轻负担'], halal: false, mealTypes: ['breakfast', 'lunch'], nutrition: { calories: 390, protein: 21, fat: 12, carbs: 48 }, expandedNutrition: { fiber: 5.2, sodium: 420, sugar: 5, calcium: 86, iron: 2.5 }, rating: 4.5, reviewCount: 32, sales: 180, image: '🥪', imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80', description: '图书馆学习间隙的便携选择。' },
  { id: 'd-innovation-rice', stallId: 'e-fast', name: '科创双拼饭', price: 14, taste: '酱香', cuisine: '快餐', ingredients: ['鸡肉', '豆腐', '米饭'], tags: ['快餐', '双拼'], halal: false, mealTypes: ['lunch', 'dinner'], nutrition: { calories: 610, protein: 31, fat: 18, carbs: 79 }, expandedNutrition: { fiber: 3.4, sodium: 720, sugar: 5, calcium: 94, iron: 3.2 }, rating: 4.3, reviewCount: 29, sales: 205, image: '🍛', imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80', description: '快速出餐的双拼套餐。' },
];

export const reviews = [
  { id: 'r1', targetType: 'dish', targetId: 'd-chicken-bowl', user: '小林', rating: 5, content: '鸡胸肉不柴，黑椒味很稳，减脂期常点。', createdAt: '2026-06-18' },
  { id: 'r2', targetType: 'dish', targetId: 'd-beef-noodle', user: '阿宁', rating: 5, content: '汤热，肉量比预期多，清真同学很方便。', createdAt: '2026-06-21' },
  { id: 'r3', targetType: 'dish', targetId: 'd-egg-tomato', user: '晨晨', rating: 4, content: '便宜快，赶课的时候不用纠结。', createdAt: '2026-06-23' },
  { id: 'r4', targetType: 'dish', targetId: 'd-liangpi', user: '小王', rating: 5, content: '天热吃凉皮太舒服了，酸辣味道正宗。', createdAt: '2026-07-05' },
  { id: 'r5', targetType: 'dish', targetId: 'd-liangpi', user: '小李', rating: 4, content: '夏天必点，量可以再多一点就完美了。', createdAt: '2026-07-08' }
];

export const userDishPreferences = [
  { userId: 'u-demo-student', dishId: 'd-chicken-bowl', favorite: 1, eatenCount: 8, drawnCount: 12 },
  { userId: 'u-demo-student', dishId: 'd-liangpi', favorite: 1, eatenCount: 5, drawnCount: 7 },
  { userId: 'u-demo-student', dishId: 'd-beef-noodle', favorite: 0, eatenCount: 3, drawnCount: 6 },
  { userId: 'u-demo-student', dishId: 'd-salad', favorite: 0, eatenCount: 2, drawnCount: 4 },
  { userId: 'u-demo-student', dishId: 'd-egg-tomato', favorite: 0, eatenCount: 6, drawnCount: 10 }
];

export const campusEnvironment = {
  tenantId: 'default',
  temperature: 34,
  weatherLabel: '晴热'
};
